name: AutoSave Branch Sync

on:
  push:
    branches: [  main ]
     

jobs:
  autosave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "KhayelihleM"
          git config user.email "khayahlanti@gmail.com"

      - name: Push to autosave branch
        run: |
          git fetch origin
          git checkout -B autosave
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:autosave --force
